---
abstract: 'Load a McBain API as a Gearman worker'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  McBain: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: McBain-WithGearmanXS
requires:
  Carp: 0
  Gearman::XS: 0
  Gearman::XS::Worker: 0
  JSON: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/McBain-WithGearmanXS
  repository: https://github.com/ido50/McBain-WithGearmanXS.git
version: 1.001000
